apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    name: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          image: "fluent/fluentd-kubernetes-daemonset:v1.14.6-debian-elasticsearch7-1.0"
          env:
            - name: FLUENTD_CONF
              value: ../../../etc/fluent/fluent.conf
          ports:
          - name: metrics
            containerPort: 24231
            protocol: TCP
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
            - mountPath: /etc/fluent
              name: etcfluentd-main
            - mountPath: /etc/fluent/config.d/
              name: etcfluentd-config
            - name: fluentd-custom-cm-fluentd-prometheus-conf
              mountPath: /etc/fluent/fluentd-prometheus-conf.d
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - configMap:
            name: fluentd-main
          name: etcfluentd-main
        - configMap:
            name: fluentd-config
          name: etcfluentd-config
        - name: fluentd-custom-cm-fluentd-prometheus-conf
          configMap:
            name: fluentd-prometheus-conf
